name = "Surrogates"
uuid = "6fc51010-71bc-11e9-0e15-a3fcc6593c49"
authors = ["ludoro <ludovicobessi@gmail.com>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
LIBSVM = "b1bec4e5-fd48-53fe-b0cb-9723c09d164b"
LatinHypercubeSampling = "a5e1c1ea-c99a-51d3-a14d-a9a37257b02d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Sobol = "ed01d8cd-4d21-5b2a-85b4-cc3bdc58bad4"
Tracker = "9f7883ad-71c0-57eb-9f7f-b5c9e6d3789c"
XGBoost = "009559a3-9522-5dbb-924b-0b6ed2b22bb9"

[compat]
DataFrames = "0.19"
Distributions = "0.21"
Flux = "0.9"
GLM = "1.3"
LIBSVM = "0.3"
LatinHypercubeSampling = "1.2"
Sobol = "1.3"
Tracker = "0.2"
XGBoost = "0.4"
julia = "1"

[extras]
Cubature = "667455a9-e2ce-5579-9412-b964f529a492"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Tracker = "9f7883ad-71c0-57eb-9f7f-b5c9e6d3789c"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
test = ["QuadGK", "Cubature", "ForwardDiff", "Tracker", "Zygote"]
